### ISSUE TITLE
Dominance GRM? 

### ISSUE THREAD

**Issue by jpiaskowski** [prmunoz/AGHmatrix#25]
Hello,

Would you be interested in adding dominance genomic relationship matrices to AGHmatrix (I see there is an option for a pedigree-based one)? I've been working on some dominance functions that could use a home. There's some older code in my [repo](https://github.com/jpiaskowski/Genomic-Dominance-Relationship-Matrix), but, I've been refactoring that so it's more streamlined and faster. If you're interested, I can prep a pull request. 

Cheers,

Julia

**Comment by rramadeu** [comment]
Hi Julia,
Thanks for sending it! I really appreciate it!

Here is Rodrigo, AGHmatrix maintainer. In fact, the package already have some dominance GRMs implemented. Probably I need to let their presence clearer... For diploids there are the ones from Su 2012 and Vitezica 2013:

```
data(snp.pine)
Gmatrix.Su <- Gmatrix(snp.pine, method="Su", missingValue=-9, maf=0.05)
Gmatrix.Vitezica <- Gmatrix(snp.pine, method="Vitezica", missingValue=-9, maf=0.05)
```

For autopolyploids, there is the one from Endelman 2018 which is regarding digenic-dominant effects

```
Gmatrix.Endelman <- Gmatrix(markersdata, method="Endelman", ploidy=4) 
```

Sorry but I'm not aware of the methods of the GenoMatrix paper. From your codes, I believe it is similar to the one that we called Vitezica, can you check it?

If I'm wrong, I would be really glad if you could prep the pull request! Then, also add yourself in the description file,

Best regards,
Rodrigo

**Comment by jpiaskowski** [comment]
The Su 2012 method is called the "centered dominance relationship matrix" and the Viticeza  2013 method is called the "normalised dominance genetic relationship" in GenoMatrix. Thanks for letting me know. For some reason, I did not see those methods when I first looked through the AGHmatrix documentation. 

Great package! I've been looking for one-stop-shop package for genomic relationship matrices and this is the best so far. Some other functionality I'd like to find or implement is an option for detecting and flagging highly similar individuals that prevent matrix inversion, or incorporation of scaling factors when there is strong population substructure (e.g. Makgahlela 2013, http://dx.doi.org/10.3168/jds.2012-652) or use of a combined A and G matrix when only some individuals are genotyped. Are you interested in any of these ideas?

**Comment by rramadeu** [comment]
Oh thanks, Julia! I believe I need to improve the package vignettes to show clearly what it can do...

Yes, it'd be a great opportunity to have these ideas implemented in the package, if you'd like to join you'd be really nice!

Some history about the package, it was initially developed to build numerator relationship matrices (pedigree-based) considering ploidy and double-reduction (Kerr 2012). We published a paper back in 2016 about it. Since then, I implemented several different ways to compute relationship matrices based on the need of collaborators/colleagues, the full list: i) additive pedigree-based for any even autopolyploidy (Kerr 2012 and the classic Henderson way), ii) dominance pedigree-based (as in Mrode book), iii) additive molecular-based (VanRaden and Yang) for diploid, iv) dominance molecular-based (Vitezica and Su), v) additive molecular based (VanRaden adapted) for autopolyploidy, vi) non-additive molecular based (as Slater 2016 and Endelman 2018) for autopolyploidy. vii) combined A and G matrix we have the one proposed by Munoz 2014 (http://www.genetics.org/content/198/4/1759) in the function Hmatrix. This last matrix combines both information in an averaged and weighted matrix, and the application is more adapted when you have many genotyped individuals, it doesn't propagate the information as the one from Vitezica... I didn't implement/study the combined matrix from Vitezica group, is this one that you are referring to?  It would be really good to have this kind of matrix in the package.

Nowadays, the package just alerts if the matrix is not positive-definite, but still misses strategies like these ones you mentioned. And, I'm working on new parametrizations for autopolyploid molecular matrices, hopefully, it'll be implemented by next month.

About publishing, I don't know if you are interested in publishing, the only paper about the package is the one of 2016 and since then we do have a lot of updates. If you want to, after these new implementations we could perfectly write a technical note/small article about them in an updated 2.0 version...

Rodrigo

**Comment by jpiaskowski** [comment]
Excellent, thanks for the background - that's helpful to read about.  I'll work on the functions I suggested above for AGH-matrix.  The combined A+G matrix I was thinking of is discussed in [Martini et al 2018](https://gsejournal.biomedcentral.com/articles/10.1186/s12711-018-0386-x) (among other papers). It is to implement a combined analysis for genotyped and non-genotyped individuals using what genotypic information is available and relying on pedigree information for the rest. There's a whole wealth of active research into genomic relationship matrices, but very little of that is actually implemented in software for routine usage.
