### ISSUE TITLE
 Gmatrix() has a bug when using the submatrix!

### ISSUE THREAD

**Issue by luansheng** [prmunoz/AGHmatrix#37]
Dear prmunoz

AGHmatrix is an excellent package for making clear the relationship among individuals. 

A bug happened when using the sub snp matrix. No value is returned when running Gmatrix() using the following code. 

> Gmatrix.VanRaden <- Gmatrix(snp.pine[1:3,1:4853], method="VanRaden", missingValue=-9, maf=0.05)
Initial data: 
	Number of Individuals: 3 
	Number of Markers: 4853 

Missing data check: 
	Total SNPs: 4853 
	 0 SNPs dropped due to missing data threshold of 1 
	Total of: 4853  SNPs 
MAF check: 
	 NA SNPs dropped with MAF below 0.05 
	Total: NA  SNPs 
Monomorphic check: 
	No monomorphic SNPs 
Summary check: 
	Initial:  4853 SNPs 
	Final:  1986  SNPs ( 2867  SNPs removed) 
 
Completed! Time = 0.78  seconds 
> Gmatrix.VanRaden[1:3,1:3]
        1087120 1085618 1091040
1087120     NaN     NaN     NaN
1085618     NaN     NaN     NaN
1091040     NaN     NaN     NaN

However, Gmatrix run rightly when the method is assigned as “Yang” and maf is assigned.

> Gmatrix.Yang <- Gmatrix(snp.pine[1:3,1:4853], method="Yang", missingValue=-9, maf=0.05)
Initial data: 
	Number of Individuals: 3 
	Number of Markers: 4853 

Missing data check: 
	Total SNPs: 4853 
	 0 SNPs dropped due to missing data threshold of 1 
	Total of: 4853  SNPs 
MAF check: 
	 NA SNPs dropped with MAF below 0.05 
	Total: NA  SNPs 
Monomorphic check: 
	No monomorphic SNPs 
Summary check: 
	Initial:  4853 SNPs 
	Final:  1986  SNPs ( 2867  SNPs removed) 
 
Completed! Time = 0.41  seconds 
> Gmatrix.Yang
            1087120     1085618     1091040
1087120  0.96446871 -0.06772787 -0.06643657
1085618 -0.06772787  0.86496325 -0.18419534
1091040 -0.06643657 -0.18419534  0.86395357

Moreover, Gmatrix run wrongly when maf is not assigned.

> Gmatrix.VanRaden <- Gmatrix(snp.pine[1:3,1:4853], method="VanRaden", missingValue=-9)
Initial data: 
	Number of Individuals: 3 
	Number of Markers: 4853 

Missing data check: 
	Total SNPs: 4853 
	 0 SNPs dropped due to missing data threshold of 1 
	Total of: 4853  SNPs 
MAF check: 
Error in if (any(snps.low)) { : missing value where TRUE/FALSE needed

I am looking forward to your reply.

Sheng Luan 
YSFRI

**Comment by rramadeu** [comment]
Hi Sheng Luan,

Thanks for the message,

This might be because you have markers in this subset with zero variance and/or all markers with missing value. You can use one of the following solutions:

**Solution 1**
You are supposed to use those methods with large number of individuals that represent a population. If you want to subset individuals, we usually built the matrix with all the individuals than subset the individuals from this big matrix. As:

```
Gmatrix.VanRaden <- Gmatrix(snp.pine, method="VanRaden", missingValue=-9)
Gsubset <- Gmatrix.VanRaden[1:3,1:3]
```
In such way you account for the allele frequency within the whole population.

**Solution 2**
If you really want to use the way you are describing, you can solve it using the impute.method="mean" option or doing some filtering for non-informative markers before running the Gmatrix function. That would mathematically solve the issue. But I wouldn't recommended it since it won't consider the population allele frequency.

Let me know if any of these solutions work for you and thanks for using the AGHmatrix! 

Rodrigo

**Comment by luansheng** [comment]
HI Rodrigo:

Many thanks for your reply. Two solutions are useful for me. But I think that the codes for Gmatrix function need to be modified because the default value (0.05) of the maf parameter may not be considered when something go wrong.
